name: CI for Renovate

on:
  push:
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:
  call:
    uses: korosuke613/actions/.github/workflows/renovate.yaml@main
    secrets:
      GH_PAT_FOR_RENOVATE: ${{ secrets.GH_PAT_FOR_RENOVATE }}
